### ISSUE TITLE
psr-0 autoloading standard

### ISSUE THREAD

**Issue by bpedroza** [dcarbone/php-fhir-generated#13]
Getting errors with composer for the following classes not complying with psr-0 autoloading standards (because of underscore in name):
Class DCarbone\PHPFHIRGenerated\DSTU2\FHIRElement\FHIRMeasmnt_Principle
Class DCarbone\PHPFHIRGenerated\DSTU2\FHIRStringPrimitive\FHIRMeasmnt_PrincipleList
Class DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRElement\FHIRMeasmnt_PrincipleTest
Class DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRStringPrimitive\FHIRMeasmnt_PrincipleListTest

https://www.php-fig.org/psr/psr-0/#underscores-in-namespaces-and-class-names

**Comment by dcarbone** [comment]
Could you provide the error you're seeing?  This package follows [PSR-4](https://www.php-fig.org/psr/psr-4/) standards.

**Comment by bpedroza** [comment]
Sure - here are he errors:


> Class DCarbone\PHPFHIRGenerated\DSTU2\FHIRElement\FHIRMeasmnt_Principle located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\FHIRElement\FHIRMeasmnt_Principle.php does not comply with psr-0 autoloading standard. Skipping.                                                                   
> Class DCarbone\PHPFHIRGenerated\DSTU2\FHIRStringPrimitive\FHIRMeasmnt_PrincipleList located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\FHIRStringPrimitive\FHIRMeasmnt_PrincipleList.php does not comply with psr-0 autoloading standard. Skipping.                                           
> Class DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRElement\FHIRMeasmnt_PrincipleTest located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRElement\FHIRMeasmnt_PrincipleTest.php does not comply with psr-0 autoloading standard. Skipping.                                 
> Class DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRStringPrimitive\FHIRMeasmnt_PrincipleListTest located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRStringPrimitive\FHIRMeasmnt_PrincipleListTest.php does not comply with psr-0 autoloading standard. Skipping.

See the link I provided above about the issue with the underscores in the name.
