### ISSUE TITLE
PSR-0 autoloading issue

### ISSUE THREAD

**Issue by bpedroza** [dcarbone/php-fhir-generated#17]
See #13 
I am opening a new issue as the referenced issue was closed as completed incorrectly.

Per the request in that issue here is the error output from composer:

> Class DCarbone\PHPFHIRGenerated\DSTU2\FHIRElement\FHIRMeasmnt_Principle located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\FHIRElement\FHIRMeasmnt_Principle.php does not comply with psr-0 autoloading standard. Skipping.
> Class DCarbone\PHPFHIRGenerated\DSTU2\FHIRStringPrimitive\FHIRMeasmnt_PrincipleList located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\FHIRStringPrimitive\FHIRMeasmnt_PrincipleList.php does not comply with psr-0 autoloading standard. Skipping.
> Class DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRElement\FHIRMeasmnt_PrincipleTest located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRElement\FHIRMeasmnt_PrincipleTest.php does not comply with psr-0 autoloading standard. Skipping.
> Class DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRStringPrimitive\FHIRMeasmnt_PrincipleListTest located in C:/sites/jte/vendor/dcarbone/php-fhir-generated/src\DCarbone\PHPFHIRGenerated\DSTU2\PHPFHIRTests\FHIRStringPrimitive\FHIRMeasmnt_PrincipleListTest.php does not comply with psr-0 autoloading standard. Skipping.

Quoted from the link I provided in #13 about the issue with the underscores in the name:

> Underscores in Namespaces and Class Names
> \namespace\package\Class_Name => /path/to/project/lib/vendor/namespace/package/Class/Name.php
> \namespace\package_name\Class_Name => /path/to/project/lib/vendor/namespace/package_name/Class/Name.php
> The standards we set here should be the lowest common denominator for painless autoloader interoperability. You can test that you are following these standards by utilizing this sample SplClassLoader implementation which is able to load PHP 5.3 classes.

**Comment by dcarbone** [comment]
This repository does not implement PSR-0, it implements PSR-4: https://www.php-fig.org/psr/psr-4/

**Comment by dcarbone** [comment]
I have updated this repo to use psr-4.
