### ISSUE TITLE
Should each FHIR version be released as a separate version?

### ISSUE THREAD

**Issue by mmcev106** [dcarbone/php-fhir-generated#6]
One of the side effects of having all FHIR classes in a single released version of this package is that you have to set up exclude rules in your IDE to make sure automatic imports find the class for the FHIR version you're interested in.  I also set up an exclude for searches.   Sheer package size might be a consideration as well.  @dcarbone, I saw you had some old versioned branches where it you'd experimented with splitting them up.  What are your thoughts on using github/composer versions (or branches) going forward?  This is not a big deal, so no rush.  I just wanted to open the discussion.

**Comment by dcarbone** [comment]
I had some concern about this as well, but maintaining multiple branches / repos is time-prohibitive at this point.  Eventually a repo-per-version will happen, but I have had to pivot on to other things for the moment.

You could utilize the generator itself to generate for your specific server, as well, which was the original intent.  This is meant as a launching-off point, primarily.

**Comment by dcarbone** [comment]
alternatively, i run a nomad + docker stack at home for some other builds, if you want to come up with a container that builds specific versions then pushes to specific repos and tags them, i'd be grateful :)

**Comment by mmcev106** [comment]
Thanks @dcarbone, I'll definitely keep that in mind.  We might end up this lib quite a bit long term.
