### ISSUE TITLE
FHIRCodePrimitive validation

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir-generated#7]
Hey @dcarbone ,

I noticed you removed ```_isValid()``` method from ```FHIRCodePrimitive``` sub-classes (those List classes). I also noticed you added some prep work in order to implement validation of data for these classes. Any idea when this would be implemented? Thanks.

**Comment by dcarbone** [comment]
Not just yet, that functionality is still a bit in-flux at the moment.  More immediately, I am working on a way to generate better tests to validate the json unmarshalling -> marshalling workflow as part of the phpunit test cases.

I would like to have something in place within the next few weeks, however.

**Comment by dcarbone** [comment]
@shehi: i have finished the initial validation implementation with v2.0.4.

Let me know if this fits your purposes.

**Comment by shehi** [comment]
Works well, thanks a lot !
