### ISSUE TITLE
FHIRUnsignedIntPrimitive::getValue() type "string"?!

### ISSUE THREAD

**Issue by shehi** [dcarbone/php-fhir-generated#8]
Hey @dcarbone ,

https://github.com/dcarbone/php-fhir-generated/blob/52075aac90a167a40097ba4329544c5e1aa44856/src/DCarbone/PHPFHIRGenerated/R4/FHIRUnsignedIntPrimitive.php#L151

Why the return value of this is marked as "string" when it can easily be "int"? It's counterpart `FHIRPositiveIntegerPrimitive` has "int" typing tho.

**Comment by dcarbone** [comment]
@shehi: because PHP has no concept of an unsigned int, and any value requiring the 64th bit to be `1` will cause the number returned to flip to negative.
